spring:
  application:
    name: eureka-client-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9003

feign:
    hystrix:
        enabled: true # 开启hystrix